// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUQ8ca-7owhmXOhiStTYmQ27pnq8DeR2E',
    appId: '1:457057212276:web:b7677107adc27f2a68fe21',
    messagingSenderId: '457057212276',
    projectId: 'testador-5b80a',
    authDomain: 'testador-5b80a.firebaseapp.com',
    databaseURL: 'https://testador-5b80a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'testador-5b80a.appspot.com',
    measurementId: 'G-WZJ89Z2REV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-GgCIRxVrrwxzokfZBRB5qVdGjY9rdGo',
    appId: '1:457057212276:android:7df45c2b8b47aca068fe21',
    messagingSenderId: '457057212276',
    projectId: 'testador-5b80a',
    databaseURL: 'https://testador-5b80a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'testador-5b80a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyHcTwox7cNXxDbeM-6MgRO7kQan1Gq84',
    appId: '1:457057212276:ios:3d2c924c881d85e868fe21',
    messagingSenderId: '457057212276',
    projectId: 'testador-5b80a',
    databaseURL: 'https://testador-5b80a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'testador-5b80a.appspot.com',
    iosClientId: '457057212276-6asomabq3l14rvrkcgse7c3aom58iktq.apps.googleusercontent.com',
    iosBundleId: 'com.example.testador',
  );
}
